language: node_js
node_js:
  - "stable"
npm: true
cache:
  directories:
    - "node_modules"
deploy:
  provider: heroku
  api_key:
  secure: "3Y1ZXsh1noWelqwrPvDqwaVUAiN1bEtFz0BiAHCXjXkzJV2dx7HfA+EHparuT3IyXrBVQaDezCv4IIhh5+t+4c1Bd7wOinJJ5dHBJOhkH+jz2EnvNGamptaRNKrtS8fzyTMLnlLoB7X+Zsc36YUTnqiKpX0rfYKJv5lFaMDQByPPCM37PQLM9U0m3a23brqFVoymjrxy+kTmXnuo+Gf3WTMdIGUE2PMzL9THZWL0a6WpU3aW1R7JGNEcrb8qMJ83ctm9eblMZzs01uSaAZ+KzTBIBEsIQ00oCKmbpthrvVPwhqGVrRbAgfXdmHYWktM61/cb2svlLKIPgdROKyUtCuK1NKcr4h3JNW58X0NAhSiMe4viD79WbfA7Fb2SZ4dRfFswW4OWVHSWtVPeE2GPklrla1rf/v4zOE/beU0W/IUyJwJXrs1//suJx31aHWcKdG7yDiMIHkOJawluSiFnUTDiLgBtho5/zgLEFL1HLgjM+qS3pJ5WTj+k9wMYu0ZFTgq4wFtzJaLCxPqIi/gwWj5yeAY6p+Ie3bCywarWmaMS2JfX9Z73nJBl54PHAVptcnZoFLP9oSI7YU1XF+jWrSPNtKPfuSuz3uSyQg4P17zQ8Y4Hg+80OBKr+FTm8dSdS4fSwAnrT84YOIHX274ByVYUouADL+GYG2JGgRfD4zE="


